In [3]:
import numpy as np

MAX_ITER = 500
EPSILON = 1e-10
TOLERANCE = 1e-5

In [4]:
def initializeModel(K, d):
    np.random.seed(0)
    pi = np.random.rand(K)
    pi = pi / np.sum(pi)

    np.random.seed(0)
    mu = np.random.normal(0, 3, size=(K, d))

    np.random.seed(0)
    S = np.random.rand(K, d) + 0.5

    return pi, mu, S



In [5]:
print(initializeModel(4, 3))
a, b, c = initializeModel(4,3)

(array([0.2275677 , 0.29655611, 0.24993822, 0.22593797]), array([[ 5.29215704,  1.20047163,  2.93621395],
       [ 6.7226796 ,  5.60267397, -2.93183364],
       [ 2.85026525, -0.45407162, -0.30965656],
       [ 1.23179551,  0.43213071,  4.36282052]]), array([[1.0488135 , 1.21518937, 1.10276338],
       [1.04488318, 0.9236548 , 1.14589411],
       [0.93758721, 1.391773  , 1.46366276],
       [0.88344152, 1.29172504, 1.02889492]]))


In [11]:
def GMM(X, K_RANGE):
    N, d = X.shape
    pi, mu, S = initializeModel(K_RANGE, d)
    r_log = np.zeros((N, K_RANGE))
    loss = [0] * MAX_ITER

    for iter in range(MAX_ITER):
        for k in range(K_RANGE):
            rlog[:,k] = np.log(pi[k] + EPSILON) - 0.5 * np.sum(np.log(S[k] + EPSILON)) - 0.5 * np.dot((X-mu[k]) ** 2, 1/(S[k] + EPSILON))
        
        r_total = logsumexp(rlog, axis=1)
        rlog = rlog - r_total[:,None]
        loss.append(-np.sum(r_total))

        if iter > 1 and abs(loss[iter] - loss[iter-1]) <= tol * abs(loss[iter]):
            break
        
        r = np.exp(rlog)
        r_total_i_wise = np.sum(r, axis=0)
        pi = r_total_i_wise / n
        mu = np.dot(r.T, X) / (r_total_i_wise[:,None] + EPSILON)
        S = np.dot(r.T, X ** 2) / (r_total_i_wise[:,None] + EPSILON) - mu ** 2

    return pi, mu, S, loss

In [10]:
X = np.loadtxt(open("../gmm_dataset.csv", "rb"), delimiter=",")

# X = np.array(
#     [
#     [1,2,2,1,2],
#     [4,2,1,2,3],
#     [4,3,1,2,3],
#     [3,1,2,3,4]
#     ]
# )
for k in range(10):
    pi, mu, S, loss = GMM(X, 3)
    print(loss)

NameError: name 'self' is not defined

In [9]:
X = np.array(
    [
        [2,2,3,4,5],
        [4,3,2,2,4],
        [4,6,5,4,3]
    ]
)
print(X.shape)
n, d = X.shape

mu = np.array([
    [2,2,2,2,2],
    [1,1,1,1,1]
])

S = np.array([1,2,1,2,2])

print(X-mu[1])
temp = (X-mu[1])**2
print(temp)
print(1/S)
temp = np.dot(temp, 1/S)
print(temp)
print(mu[1])
# print(np.sum((X-mu[1])**2, axis=1))
print(np.linalg.norm(X - mu[1])**2)

print(np.power(X-mu[1], -1/2))


(3, 5)
[[1 1 2 3 4]
 [3 2 1 1 3]
 [3 5 4 3 2]]
[[ 1  1  4  9 16]
 [ 9  4  1  1  9]
 [ 9 25 16  9  4]]
[1.  0.5 1.  0.5 0.5]
[18. 17. 44.]
[1 1 1 1 1]
118.0
[[1.         1.         0.70710678 0.57735027 0.5       ]
 [0.57735027 0.70710678 1.         1.         0.57735027]
 [0.57735027 0.4472136  0.5        0.57735027 0.70710678]]


In [76]:
print(np.log(np.exp([1,2,3,4])))

print(X)
total = np.sum(X, axis=1)
print(total[:,None])

# print(X - total)
print(X / total[:,None])

[1. 2. 3. 4.]
[[2 2 3 4 5]
 [4 3 2 2 4]
 [4 6 5 4 3]]
[[16]
 [15]
 [22]]
[[0.125      0.125      0.1875     0.25       0.3125    ]
 [0.26666667 0.2        0.13333333 0.13333333 0.26666667]
 [0.18181818 0.27272727 0.22727273 0.18181818 0.13636364]]


In [79]:
print(X)
print(mu[1])
print(np.power(X, 2))

[[2 2 3 4 5]
 [4 3 2 2 4]
 [4 6 5 4 3]]
[1 1 1 1 1]
[[ 4  4  9 16 25]
 [16  9  4  4 16]
 [16 36 25 16  9]]


In [258]:
X = np.array(
    [
        [2,2,3,4,5],
        [4,3,2,2,4],
        [4,6,5,4,3]
    ]
)

X_0 = X[0][:,None]
X_0_trans = X[0][:,None].T
print(X_0, X_0_trans)
print(X_0.dot(X_0_trans))

[[2]
 [2]
 [3]
 [4]
 [5]] [[2 2 3 4 5]]
[[ 4  4  6  8 10]
 [ 4  4  6  8 10]
 [ 6  6  9 12 15]
 [ 8  8 12 16 20]
 [10 10 15 20 25]]
